/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AppNavbar from "../components/app-navbar";
import Providers from "../components/providers";
import ChatWidget from "./ChatWidget";
import "./globals.css";

const museoModerno = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Convonest Analytics",
  description: "Generated by Convonest Tech Pvt Ltd.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Fira+Code:wght@300..700&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=MuseoModerno:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" type="image/png" href="/images/icon.png" />
        {/* Optional: Add different sizes for better support */}
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/icon.png"
        />
      </head>
      <body className={`${museoModerno.className} flex min-h-screen flex-col`}>
        <Providers>
          <div className="fixed top-0 z-50 w-full bg-white shadow-md">
            <AppNavbar />
          </div>
          <main className="mt-10 flex-grow">{children}</main>
          <ChatWidget />
        </Providers>
      </body>
    </html>
  );
}
